In [110]:
import pandas as pd
import numpy as np

model 1

In [111]:
notification  = pd.read_csv("notifai_final_realistic_dataset.csv")

In [112]:
notification

,notification_id,app_name,package_name,notification_text,category,sender_type,message_length,contains_urgent_words,time_of_day,weekday,...,app_open_frequency,notification_open_rate,notification_ignore_rate,average_reply_time_seconds,session_duration_minutes,notification_clicked,notification_dismissed,model1_priority_label,model1_priority_encoded,final_priority_score
0,1,Amazon,com.amazon,Story update available,shopping,system,31,0,evening,Thursday,...,31,0.69,0.31,409,42,1,0,LOW,0,1.9
1,2,YouTube,com.youtube,Story update available,social,promo,31,0,afternoon,Friday,...,52,0.12,0.88,486,66,1,1,LOW,0,2.2
2,3,Telegram,com.telegram,Meeting starts rn ⚡,message,system,28,1,morning,Sunday,...,50,0.28,0.72,408,1,0,1,HIGH,2,6.6
3,4,Instagram,com.instagram,Emergency at home 😭 reply pls,social,promo,30,1,afternoon,Sunday,...,8,0.52,0.48,147,82,1,0,HIGH,2,5.6
4,5,LinkedIn,com.linkedin,New req on LinkedIn 🤝,social,work,22,0,night,Saturday,...,23,0.47,0.53,773,30,1,0,MEDIUM,1,4.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,5396,YouTube,com.app,Emergency update from home. Please check your ...,shopping,friend,127,1,night,Saturday,...,9,0.56,0.05,952,71,1,1,HIGH,2,7.4
5396,5397,WhatsApp,com.app,Bro the professor just announced that the assi...,work,work,145,1,evening,Sunday,...,57,0.97,0.39,365,76,0,0,MEDIUM,1,6.9
5397,5398,YouTube,com.app,Bro the professor just announced that the assi...,shopping,friend,145,1,night,Tuesday,...,48,0.82,0.64,147,46,0,0,MEDIUM,1,5.8
5398,5399,Instagram,com.app,Your favorite creator just uploaded an exclusi...,productivity,friend,118,1,night,Monday,...,27,0.99,0.83,546,34,0,1,LOW,0,1.5
5399,5400,Slack,com.app,Important notice: Internal examinations are li...,shopping,work,122,0,morning,Thursday,...,16,0.66,0.05,1128,73,1,1,MEDIUM,1,6.0

In [113]:
notification.isnull().sum()

notification_id                 0
app_name                        0
package_name                    0
notification_text               0
category                        0
sender_type                     0
message_length                  0
contains_urgent_words           0
time_of_day                     0
weekday                         0
screen_on                       0
battery_level                   0
headset_connected               0
current_activity                0
notification_frequency_today    0
app_usage_minutes_today         0
app_open_frequency              0
notification_open_rate          0
notification_ignore_rate        0
average_reply_time_seconds      0
session_duration_minutes        0
notification_clicked            0
notification_dismissed          0
model1_priority_label           0
model1_priority_encoded         0
final_priority_score            0
dtype: int64

In [114]:
notification.nunique()

notification_id                 5400
app_name                          10
package_name                      11
notification_text                 86
category                           6
sender_type                        5
message_length                    23
contains_urgent_words              2
time_of_day                        4
weekday                            7
screen_on                          2
battery_level                     91
headset_connected                  2
current_activity                   5
notification_frequency_today      60
app_usage_minutes_today          319
app_open_frequency                60
notification_open_rate            96
notification_ignore_rate          96
average_reply_time_seconds      1175
session_duration_minutes          90
notification_clicked               2
notification_dismissed             2
model1_priority_label              3
model1_priority_encoded            3
final_priority_score             101
dtype: int64

In [115]:
notification['app_name'].value_counts()

app_name
Instagram          606
Google Calendar    571
Amazon             559
Gmail              542
LinkedIn           535
Telegram           533
Slack              532
WhatsApp           516
YouTube            510
Discord            496
Name: count, dtype: int64

In [116]:
notification.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5400 entries, 0 to 5399
Data columns (total 26 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   notification_id               5400 non-null   int64
 1   app_name                      5400 non-null   object
 2   package_name                  5400 non-null   object
 3   notification_text             5400 non-null   object
 4   category                      5400 non-null   object
 5   sender_type                   5400 non-null   object
 6   message_length                5400 non-null   int64
 7   contains_urgent_words         5400 non-null   int64
 8   time_of_day                   5400 non-null   object
 9   weekday                       5400 non-null   object
 10  screen_on                     5400 non-null   int64
 11  battery_level                 5400 non-null   int64
 12  headset_connected             5400 non-null   int64
 13  current_activity              5400 non-null   object
 14  notification_frequency_today  5400 non-null   int64
 15  app_usage_minutes_today       5400 non-null   int64
 16  app_open_frequency            5400 non-null   int64
 17  notification_open_rate        5400 non-null   float64
 18  notification_ignore_rate      5400 non-null   float64
 19  average_reply_time_seconds    5400 non-null   int64
 20  session_duration_minutes      5400 non-null   int64
 21  notification_clicked          5400 non-null   int64
 22  notification_dismissed        5400 non-null   int64
 23  model1_priority_label         5400 non-null   object
 24  model1_priority_encoded       5400 non-null   int64
 25  final_priority_score          5400 non-null   float64
dtypes: float64(3), int64(14), object(9)
memory usage: 1.1+ MB

In [117]:
def weekday_and_weekend(day):
    if day in ['Saturday','Sunday']:
        return 0
    else:
        return 1

In [118]:
notification['weekday'] = notification['weekday']. apply(weekday_and_weekend)

In [119]:
notification['weekday']

0       1
1       1
2       0
3       0
4       0
       ..
5395    0
5396    0
5397    1
5398    1
5399    1
Name: weekday, Length: 5400, dtype: int64

In [120]:
notification

,notification_id,app_name,package_name,notification_text,category,sender_type,message_length,contains_urgent_words,time_of_day,weekday,...,app_open_frequency,notification_open_rate,notification_ignore_rate,average_reply_time_seconds,session_duration_minutes,notification_clicked,notification_dismissed,model1_priority_label,model1_priority_encoded,final_priority_score
0,1,Amazon,com.amazon,Story update available,shopping,system,31,0,evening,1,...,31,0.69,0.31,409,42,1,0,LOW,0,1.9
1,2,YouTube,com.youtube,Story update available,social,promo,31,0,afternoon,1,...,52,0.12,0.88,486,66,1,1,LOW,0,2.2
2,3,Telegram,com.telegram,Meeting starts rn ⚡,message,system,28,1,morning,0,...,50,0.28,0.72,408,1,0,1,HIGH,2,6.6
3,4,Instagram,com.instagram,Emergency at home 😭 reply pls,social,promo,30,1,afternoon,0,...,8,0.52,0.48,147,82,1,0,HIGH,2,5.6
4,5,LinkedIn,com.linkedin,New req on LinkedIn 🤝,social,work,22,0,night,0,...,23,0.47,0.53,773,30,1,0,MEDIUM,1,4.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,5396,YouTube,com.app,Emergency update from home. Please check your ...,shopping,friend,127,1,night,0,...,9,0.56,0.05,952,71,1,1,HIGH,2,7.4
5396,5397,WhatsApp,com.app,Bro the professor just announced that the assi...,work,work,145,1,evening,0,...,57,0.97,0.39,365,76,0,0,MEDIUM,1,6.9
5397,5398,YouTube,com.app,Bro the professor just announced that the assi...,shopping,friend,145,1,night,1,...,48,0.82,0.64,147,46,0,0,MEDIUM,1,5.8
5398,5399,Instagram,com.app,Your favorite creator just uploaded an exclusi...,productivity,friend,118,1,night,1,...,27,0.99,0.83,546,34,0,1,LOW,0,1.5
5399,5400,Slack,com.app,Important notice: Internal examinations are li...,shopping,work,122,0,morning,1,...,16,0.66,0.05,1128,73,1,1,MEDIUM,1,6.0

feature extraction and cleaning

In [121]:
model1 = notification[[
    'notification_text',
    'app_name',
    'category',
    'message_length',
    'contains_urgent_words',
    'time_of_day',
    'weekday',
    'screen_on',
    'battery_level',
    'headset_connected',
    'notification_frequency_today',
    'model1_priority_label'
]]

In [122]:
model1['category'].value_counts()

category
social          2055
message         1038
productivity     607
email            583
shopping         560
work             557
Name: count, dtype: int64

In [123]:
model1_catagorical = model1.select_dtypes(exclude = np.number).columns.tolist()
model1_catagorical

['notification_text',
 'app_name',
 'category',
 'time_of_day',
 'model1_priority_label']

In [124]:
from numpy import test
from sklearn.preprocessing import OneHotEncoder
oe_app = OneHotEncoder(handle_unknown='ignore')
oe_sender = OneHotEncoder(handle_unknown='ignore')
oe_category = OneHotEncoder(handle_unknown='ignore')
oe_time = OneHotEncoder(handle_unknown='ignore')
oe_activity = OneHotEncoder(handle_unknown='ignore')

app_name = oe_app.fit_transform(model1[['app_name']])

In [125]:
model1 = pd.concat ([model1, pd.DataFrame(app_name.toarray(), columns=oe_app.get_feature_names_out())],axis =1)

In [126]:
model1.drop(['app_name'], inplace = True, axis = 1)

In [127]:
time_of_the_day = oe_time.fit_transform(model1[['time_of_day']])
model1 = pd.concat([model1 , pd.DataFrame(time_of_the_day.toarray(), columns = oe_time.get_feature_names_out())], axis =1)

In [128]:
model1.drop(['time_of_day'], axis =1, inplace = True)

In [129]:
category = oe_category.fit_transform(model1[['category']])
model1 = pd.concat([model1 , pd.DataFrame(category.toarray(), columns = oe_category.get_feature_names_out())], axis =1)
model1.drop(['category'], axis =1, inplace = True)

text processing

In [130]:
model1 =  model1.sample(frac= 1)

text processing and NLP

In [131]:
import emoji
text = "Emergency at home 😭 reply pls"
emoji.demojize(text)

'Emergency at home :loudly_crying_face: reply pls'

In [132]:
def demojizeing_notification(text):
    return emoji.demojize(text)



model1.loc[:, 'notification_text'] = model1['notification_text'].apply(demojizeing_notification)

In [133]:
model1.reset_index(drop = True , inplace = True)

In [134]:
model1

,notification_text,message_length,contains_urgent_words,weekday,screen_on,battery_level,headset_connected,notification_frequency_today,model1_priority_label,app_name_Amazon,...,time_of_day_afternoon,time_of_day_evening,time_of_day_morning,time_of_day_night,category_email,category_message,category_productivity,category_shopping,category_social,category_work
0,Interview confirmed :party_popper:,27,1,1,1,13,1,41,HIGH,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,Coming tomorrow bro?,24,0,1,1,56,0,49,MEDIUM,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,Bro call me rn :loudly_crying_face:,16,1,1,1,32,1,56,HIGH,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,Discussion updated pls check,23,0,0,1,15,0,20,MEDIUM,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,Sale starts rn :fire:,21,0,0,0,67,1,20,LOW,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,Team mtg starts soon :briefcase:,28,1,0,0,32,0,4,HIGH,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5396,Join meeting ASAP :technologist:,28,1,1,0,13,0,10,HIGH,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5397,Game night brooo :smiling_face_with_sunglasses:,18,0,0,1,72,0,5,MEDIUM,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5398,Join game lobby :bullseye:,18,0,1,0,72,0,47,MEDIUM,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5399,You got tagged :face_with_tears_of_joy:,25,0,0,1,37,0,50,MEDIUM,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

Lower case ,
Tokenization , 
Removing special characters ,
Removing stop words and punctuation ,
Stemming

In [135]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\KIIT\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\KIIT\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\KIIT\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [136]:
import string
from nltk .corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [137]:
def NLP(text):
    y = []
    text = text.lower()
    text = nltk.word_tokenize(text)

    for i in text:
        if i .isalnum():
            y.append(i)


    text = y[:]
    y.clear()   

    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i)  

    text = y[:]
    y.clear()

    ps = PorterStemmer()
    for i in text:
        y.append(ps.stem(i))  



    return " ".join(y)

In [138]:
model1['notification_text'] = model1['notification_text'].apply(NLP)

In [139]:
model1

,notification_text,message_length,contains_urgent_words,weekday,screen_on,battery_level,headset_connected,notification_frequency_today,model1_priority_label,app_name_Amazon,...,time_of_day_afternoon,time_of_day_evening,time_of_day_morning,time_of_day_night,category_email,category_message,category_productivity,category_shopping,category_social,category_work
0,interview confirm,27,1,1,1,13,1,41,HIGH,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
1,come tomorrow bro,24,0,1,1,56,0,49,MEDIUM,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,bro call rn,16,1,1,1,32,1,56,HIGH,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,discuss updat pl check,23,0,0,1,15,0,20,MEDIUM,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,sale start rn fire,21,0,0,0,67,1,20,LOW,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,team mtg start soon briefcas,28,1,0,0,32,0,4,HIGH,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5396,join meet asap technologist,28,1,1,0,13,0,10,HIGH,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5397,game night brooo,18,0,0,1,72,0,5,MEDIUM,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5398,join game lobbi bullsey,18,0,1,0,72,0,47,MEDIUM,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5399,got tag,25,0,0,1,37,0,50,MEDIUM,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [140]:
from sklearn.feature_extraction.text import TfidfVectorizer 
vector = TfidfVectorizer ()

In [141]:
vectorized = vector.fit_transform(model1['notification_text'])
model1 = pd.concat([model1 , pd.DataFrame(vectorized.toarray() , columns = vector.get_feature_names_out())], axis = 1)
model1.drop(['notification_text'],axis = 1 ,inplace= True)

In [142]:
model1

,message_length,contains_urgent_words,weekday,screen_on,battery_level,headset_connected,notification_frequency_today,model1_priority_label,app_name_Amazon,app_name_Discord,...,vid,video,viral,visit,vlog,wait,want,warn,watch,workshop
0,27,1,1,1,13,1,41,HIGH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,24,0,1,1,56,0,49,MEDIUM,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,16,1,1,1,32,1,56,HIGH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,23,0,0,1,15,0,20,MEDIUM,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21,0,0,0,67,1,20,LOW,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,28,1,0,0,32,0,4,HIGH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5396,28,1,1,0,13,0,10,HIGH,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5397,18,0,0,1,72,0,5,MEDIUM,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5398,18,0,1,0,72,0,47,MEDIUM,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5399,25,0,0,1,37,0,50,MEDIUM,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

train and test split

In [143]:
from sklearn.model_selection import train_test_split

In [144]:
x = model1.drop(['model1_priority_label'], axis =1)
y = model1['model1_priority_label']

In [145]:
x_train, x_test, y_train, y_test =train_test_split(x,y ,test_size = 0.3 )

In [146]:
x

,message_length,contains_urgent_words,weekday,screen_on,battery_level,headset_connected,notification_frequency_today,app_name_Amazon,app_name_Discord,app_name_Gmail,...,vid,video,viral,visit,vlog,wait,want,warn,watch,workshop
0,27,1,1,1,13,1,41,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,24,0,1,1,56,0,49,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,16,1,1,1,32,1,56,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,23,0,0,1,15,0,20,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,21,0,0,0,67,1,20,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5395,28,1,0,0,32,0,4,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5396,28,1,1,0,13,0,10,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5397,18,0,0,1,72,0,5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5398,18,0,1,0,72,0,47,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5399,25,0,0,1,37,0,50,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [147]:
y

0         HIGH
1       MEDIUM
2         HIGH
3       MEDIUM
4          LOW
         ...
5395      HIGH
5396      HIGH
5397    MEDIUM
5398    MEDIUM
5399    MEDIUM
Name: model1_priority_label, Length: 5400, dtype: object

modeling and model-scaling

In [148]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [149]:
rf_predict = rf.predict(x_test)

In [150]:
rf.score(x_test,y_test)

1.0

In [151]:
from sklearn.metrics import classification_report
print(classification_report(y_test,rf_predict))

              precision    recall  f1-score   support

        HIGH       1.00      1.00      1.00       447
         LOW       1.00      1.00      1.00       592
      MEDIUM       1.00      1.00      1.00       581

    accuracy                           1.00      1620
   macro avg       1.00      1.00      1.00      1620
weighted avg       1.00      1.00      1.00      1620

model scaling (review)

In [152]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

In [153]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
#from xgboost import XGBClassifier

In [154]:
svc = SVC(kernel='sigmoid', gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='saga', penalty='l1', max_iter=1000)
abc = AdaBoostClassifier(n_estimators=50, random_state=2)
bc = BaggingClassifier(n_estimators=50, random_state=2)
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)
#xgb = XGBClassifier(n_estimators=50,random_state=2)

In [155]:
clfs = {
    'SVC' : svc,
    'KN' : knc,
    'NB': mnb,
    'DT': dtc,
    'LR': lrc,
    'AdaBoost': abc,
    'BgC': bc,
    'ETC': etc,
    'GBDT':gbdt,
}

In [156]:
def train_classifier(clf,X_train,y_train,X_test,y_test):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    precision = precision_score(y_test,y_pred, average='weighted')

    return accuracy,precision

In [157]:
accuracy_scores = []
precision_scores = []

for name,clf in clfs.items():

    current_accuracy,current_precision = train_classifier(clf, x_train ,y_train,x_test,y_test)

    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)

    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

C:\Users\KIIT\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\KIIT\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\KIIT\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(

For  SVC
Accuracy -  0.358641975308642
Precision -  0.12862406645328456
For  KN
Accuracy -  0.6160493827160494
Precision -  0.6069591206836671
For  NB
Accuracy -  0.9709876543209877
Precision -  0.9710208940656468
For  DT
Accuracy -  0.895679012345679
Precision -  0.8991757931116536

C:\Users\KIIT\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

For  LR
Accuracy -  0.9882716049382716
Precision -  0.9883216764894749
For  AdaBoost
Accuracy -  0.8598765432098765
Precision -  0.8636179777751348
For  BgC
Accuracy -  1.0
Precision -  1.0
For  ETC
Accuracy -  1.0
Precision -  1.0
For  GBDT
Accuracy -  1.0
Precision -  1.0

In [158]:
performance_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores}).sort_values('Precision',ascending=False)
performance_df

  Algorithm  Accuracy  Precision
7       ETC  1.000000   1.000000
6       BgC  1.000000   1.000000
8      GBDT  1.000000   1.000000
4        LR  0.988272   0.988322
2        NB  0.970988   0.971021
3        DT  0.895679   0.899176
5  AdaBoost  0.859877   0.863618
1        KN  0.616049   0.606959
0       SVC  0.358642   0.128624

voting classifier

In [159]:
from sklearn.ensemble import VotingClassifier

In [160]:
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)
lrc = LogisticRegression(solver='saga', penalty='l1', max_iter=1000)
mnb = MultinomialNB()
voting = VotingClassifier(estimators=[('gbdt', gbdt), ('lrc', lrc), ('mnb', mnb)],voting='soft')

In [161]:
voting.fit(x_train,y_train)

C:\Users\KIIT\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\KIIT\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
C:\Users\KIIT\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

VotingClassifier(estimators=[('gbdt',
                              GradientBoostingClassifier(n_estimators=50,
                                                         random_state=2)),
                             ('lrc',
                              LogisticRegression(max_iter=1000, penalty='l1',
                                                 solver='saga')),
                             ('mnb', MultinomialNB())],
                 voting='soft')

In [162]:
voting_prediction = voting.predict(x_test)
print("Accuracy",accuracy_score(y_test,voting_prediction))
print("Precision",precision_score(y_test,voting_prediction,average='weighted'))

Accuracy 0.991358024691358
Precision 0.9915613652868555

In [163]:
import pickle
pickle.dump(voting,open('model1.pkl','wb'))
pickle.dump(vector,open('tfidf_vectorizer.pkl','wb'))
pickle.dump(oe_app,open('onehot_encoder_app.pkl','wb'))

pickle.dump(oe_category,open('onehot_encoder_category.pkl','wb'))
pickle.dump(oe_time,open('onehot_encoder_time.pkl','wb'))

test

In [164]:
test_notification = {
    "notification_text": "I'm breaking up with you",
    "app_name": "WhatsApp",
    "category": "social",
    "message_length": 21,
    "contains_urgent_words": 0,
    "time_of_day": "night",
    "weekday": "Friday",
    "screen_on": 1,
    "battery_level": 78,
    "headset_connected": 1,
    "notification_frequency_today": 12
}

model 2

In [165]:
model2 =  pd.read_csv('model2_priority_dataset.csv')

In [166]:
model2

,model1_priority_label,app_name,battery_level,screen_on,headset_connected,time_of_day,weekday,notification_frequency_today,app_usage_minutes_today,app_open_frequency,notification_open_rate,notification_ignore_rate,notification_clicked,notification_dismissed,priority_score
0,MEDIUM,LinkedIn,36,0,0,morning,Saturday,48,279,5,0.41,0.59,1,0,69.97
1,HIGH,Calendar,82,0,0,night,Tuesday,29,301,17,0.77,0.23,0,0,91.17
2,LOW,Instagram,32,1,0,morning,Thursday,7,183,54,0.17,0.83,1,1,27.77
3,LOW,Calendar,20,1,0,evening,Sunday,41,316,56,0.36,0.64,1,0,38.28
4,LOW,YouTube,42,0,0,morning,Thursday,18,232,40,0.02,0.98,1,0,17.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,MEDIUM,Gmail,12,0,1,night,Monday,39,47,0,0.66,0.34,1,0,64.51
4996,LOW,Twitter,95,0,0,evening,Monday,2,78,54,0.22,0.78,1,0,28.54
4997,MEDIUM,Discord,31,0,0,night,Sunday,11,216,53,0.53,0.47,1,1,89.00
4998,LOW,Teams,64,1,1,morning,Saturday,31,218,40,0.47,0.53,1,0,29.70
4999,MEDIUM,WhatsApp,43,0,1,evening,Sunday,46,279,40,0.57,0.43,0,0,56.52

In [167]:
model2['app_name']

0        LinkedIn
1        Calendar
2       Instagram
3        Calendar
4         YouTube
          ...
4995        Gmail
4996      Twitter
4997      Discord
4998        Teams
4999     WhatsApp
Name: app_name, Length: 5000, dtype: object

In [168]:
model2['weekday'] = model2['weekday'].apply(weekday_and_weekend)

In [169]:
model2

,model1_priority_label,app_name,battery_level,screen_on,headset_connected,time_of_day,weekday,notification_frequency_today,app_usage_minutes_today,app_open_frequency,notification_open_rate,notification_ignore_rate,notification_clicked,notification_dismissed,priority_score
0,MEDIUM,LinkedIn,36,0,0,morning,0,48,279,5,0.41,0.59,1,0,69.97
1,HIGH,Calendar,82,0,0,night,1,29,301,17,0.77,0.23,0,0,91.17
2,LOW,Instagram,32,1,0,morning,1,7,183,54,0.17,0.83,1,1,27.77
3,LOW,Calendar,20,1,0,evening,0,41,316,56,0.36,0.64,1,0,38.28
4,LOW,YouTube,42,0,0,morning,1,18,232,40,0.02,0.98,1,0,17.19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,MEDIUM,Gmail,12,0,1,night,1,39,47,0,0.66,0.34,1,0,64.51
4996,LOW,Twitter,95,0,0,evening,1,2,78,54,0.22,0.78,1,0,28.54
4997,MEDIUM,Discord,31,0,0,night,0,11,216,53,0.53,0.47,1,1,89.00
4998,LOW,Teams,64,1,1,morning,0,31,218,40,0.47,0.53,1,0,29.70
4999,MEDIUM,WhatsApp,43,0,1,evening,0,46,279,40,0.57,0.43,0,0,56.52

In [170]:
model2.drop(['notification_open_rate', 'notification_ignore_rate'], axis=1,inplace=True)

In [171]:
categorical_col = model2.select_dtypes(exclude= np.number).columns.tolist()
categorical_col

['model1_priority_label', 'app_name', 'time_of_day']

In [172]:
oe_model1_priority_label = OneHotEncoder(handle_unknown='ignore')
encoded_ptiority_label = oe_model1_priority_label.fit_transform(model2[['model1_priority_label']])
model2 = pd.concat([model2,pd.DataFrame(encoded_ptiority_label.toarray(),columns= oe_model1_priority_label.get_feature_names_out() )], axis = 1)

In [173]:
model2.drop(['model1_priority_label'], axis = 1, inplace = True )

In [174]:
model2

,app_name,battery_level,screen_on,headset_connected,time_of_day,weekday,notification_frequency_today,app_usage_minutes_today,app_open_frequency,notification_clicked,notification_dismissed,priority_score,model1_priority_label_HIGH,model1_priority_label_LOW,model1_priority_label_MEDIUM
0,LinkedIn,36,0,0,morning,0,48,279,5,1,0,69.97,0.0,0.0,1.0
1,Calendar,82,0,0,night,1,29,301,17,0,0,91.17,1.0,0.0,0.0
2,Instagram,32,1,0,morning,1,7,183,54,1,1,27.77,0.0,1.0,0.0
3,Calendar,20,1,0,evening,0,41,316,56,1,0,38.28,0.0,1.0,0.0
4,YouTube,42,0,0,morning,1,18,232,40,1,0,17.19,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,Gmail,12,0,1,night,1,39,47,0,1,0,64.51,0.0,0.0,1.0
4996,Twitter,95,0,0,evening,1,2,78,54,1,0,28.54,0.0,1.0,0.0
4997,Discord,31,0,0,night,0,11,216,53,1,1,89.00,0.0,0.0,1.0
4998,Teams,64,1,1,morning,0,31,218,40,1,0,29.70,0.0,1.0,0.0
4999,WhatsApp,43,0,1,evening,0,46,279,40,0,0,56.52,0.0,0.0,1.0

In [175]:
oer_app = OneHotEncoder(handle_unknown='ignore')

In [176]:
encoded_app = oer_app.fit_transform(model2[['app_name']])
model2 = pd.concat([model2 ,pd.DataFrame(encoded_app.toarray(), columns = oer_app.get_feature_names_out())], axis = 1)
model2.drop(['app_name'], inplace = True, axis= 1)

In [177]:
encoded_time = oe_time.fit_transform(model2[['time_of_day']])
model2 = pd.concat([model2, pd.DataFrame(encoded_time.toarray(),columns=oe_time.get_feature_names_out())], axis = 1)
model2.drop(['time_of_day'],axis= 1, inplace = True)

In [178]:
model2

,battery_level,screen_on,headset_connected,weekday,notification_frequency_today,app_usage_minutes_today,app_open_frequency,notification_clicked,notification_dismissed,priority_score,...,app_name_LinkedIn,app_name_Teams,app_name_Telegram,app_name_Twitter,app_name_WhatsApp,app_name_YouTube,time_of_day_afternoon,time_of_day_evening,time_of_day_morning,time_of_day_night
0,36,0,0,0,48,279,5,1,0,69.97,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,82,0,0,1,29,301,17,0,0,91.17,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,32,1,0,1,7,183,54,1,1,27.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,20,1,0,0,41,316,56,1,0,38.28,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,42,0,0,1,18,232,40,1,0,17.19,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,12,0,1,1,39,47,0,1,0,64.51,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4996,95,0,0,1,2,78,54,1,0,28.54,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4997,31,0,0,0,11,216,53,1,1,89.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4998,64,1,1,0,31,218,40,1,0,29.70,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4999,43,0,1,0,46,279,40,0,0,56.52,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [179]:
model2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 27 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   battery_level                 5000 non-null   int64
 1   screen_on                     5000 non-null   int64
 2   headset_connected             5000 non-null   int64
 3   weekday                       5000 non-null   int64
 4   notification_frequency_today  5000 non-null   int64
 5   app_usage_minutes_today       5000 non-null   int64
 6   app_open_frequency            5000 non-null   int64
 7   notification_clicked          5000 non-null   int64
 8   notification_dismissed        5000 non-null   int64
 9   priority_score                5000 non-null   float64
 10  model1_priority_label_HIGH    5000 non-null   float64
 11  model1_priority_label_LOW     5000 non-null   float64
 12  model1_priority_label_MEDIUM  5000 non-null   float64
 13  app_name_Calendar             5000 non-null   float64
 14  app_name_Discord              5000 non-null   float64
 15  app_name_Gmail                5000 non-null   float64
 16  app_name_Instagram            5000 non-null   float64
 17  app_name_LinkedIn             5000 non-null   float64
 18  app_name_Teams                5000 non-null   float64
 19  app_name_Telegram             5000 non-null   float64
 20  app_name_Twitter              5000 non-null   float64
 21  app_name_WhatsApp             5000 non-null   float64
 22  app_name_YouTube              5000 non-null   float64
 23  time_of_day_afternoon         5000 non-null   float64
 24  time_of_day_evening           5000 non-null   float64
 25  time_of_day_morning           5000 non-null   float64
 26  time_of_day_night             5000 non-null   float64
dtypes: float64(18), int64(9)
memory usage: 1.0 MB

In [180]:
x2 = model2.drop(['priority_score'], axis = 1)
y2 = model2['priority_score']

In [181]:
x2_train , x2_test , y2_train , y2_test = train_test_split(x2,y2,test_size = 0.3)

In [182]:
from sklearn . linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [183]:
lr = LinearRegression()
lr.fit(x2_train,y2_train)

LinearRegression()

In [184]:
dr = DecisionTreeRegressor()
dr.fit(x2_train,y2_train)

DecisionTreeRegressor()

In [185]:
dr_predict = dr.predict(x2_test)

In [186]:
lr_predict = lr.predict(x2_test)

In [187]:
dr.score(x2_test,y2_test)

0.7917994998727445

In [188]:
lr.score(x2_test,y2_test)

0.9082845881559752

In [189]:
  # for regression model there is no classification report rather it has MSE, R2 score, RMSE, MAE

In [190]:
from sklearn.metrics import mean_absolute_error , mean_squared_error, r2_score

In [191]:
mae = mean_absolute_error(lr.predict(x2_test),y2_test)
mae

7.329329394660379

In [192]:
mse = mean_squared_error(lr.predict(x2_test),y2_test)
rmse = np.sqrt(mse)
rmse

np.float64(9.301909408051962)

In [193]:
r2 = r2_score(lr.predict(x2_test), y2_test)
r2

0.8971836335074773

In [194]:
dr_r2 = r2_score(dr.predict(x2_test),y2_test)
dr_r2

0.7786281262212121

In [195]:
x2_test.shape

(1500, 26)

In [196]:
adj_dr_r2 = 1- ((1-r2_score(dr.predict(x2_test),y2_test))*(1500 -1))/(1500 - 1 - 28)
adj_dr_r2

0.7744143855918402

In [197]:
rf_r = RandomForestRegressor()
rf_r . fit(x2_train,y2_train)

RandomForestRegressor()

In [198]:
rf_r.predict(x2_test)

array([60.9405, 22.7216, 89.5923, ..., 68.187 , 90.4562, 19.6884],
      shape=(1500,))

In [199]:
r2_score(rf_r.predict(x2_test),y2_test)

0.8879430405742785

In [200]:
adj_rf_r_r2 = 1- ((1-r2_score(rf_r.predict(x2_test),y2_test))*(1500 -1))/(1500 - 1 - 28)
adj_rf_r_r2

0.8858100732976503

In [201]:
from sklearn.ensemble import VotingRegressor

voting_regressor = VotingRegressor(
    estimators=[
        ('lr', LinearRegression()),
        ('rf', RandomForestRegressor()),
        ('dr', DecisionTreeRegressor())
    ],
    weights=[3, 3, 1]
)

In [202]:
voting_regressor.fit(x2_train,y2_train)

VotingRegressor(estimators=[('lr', LinearRegression()),
                            ('rf', RandomForestRegressor()),
                            ('dr', DecisionTreeRegressor())],
                weights=[3, 3, 1])

In [203]:
voting_regressor_pred = voting_regressor.predict(x2_test)

In [204]:
print("R²:", r2_score(y2_test, voting_regressor_pred))

R²: 0.9037874009437319

In [205]:
pickle.dump(voting_regressor,open('model2.pkl','wb'))
pickle.dump(oe_model1_priority_label,open('onehot_encoder_model1_priority_label.pkl','wb'))

features modelwise

In [206]:
feature_order1 = model1.drop(columns=["model1_priority_label"]).columns.tolist()
feature_order1

['message_length',
 'contains_urgent_words',
 'weekday',
 'screen_on',
 'battery_level',
 'headset_connected',
 'notification_frequency_today',
 'app_name_Amazon',
 'app_name_Discord',
 'app_name_Gmail',
 'app_name_Google Calendar',
 'app_name_Instagram',
 'app_name_LinkedIn',
 'app_name_Slack',
 'app_name_Telegram',
 'app_name_WhatsApp',
 'app_name_YouTube',
 'time_of_day_afternoon',
 'time_of_day_evening',
 'time_of_day_morning',
 'time_of_day_night',
 'category_email',
 'category_message',
 'category_productivity',
 'category_shopping',
 'category_social',
 'category_work',
 '10',
 'accessori',
 'accord',
 'ad',
 'address',
 'alert',
 'along',
 'alreadi',
 'announc',
 'anoth',
 'appt',
 'arriv',
 'asap',
 'assign',
 'avail',
 'back',
 'book',
 'briefcas',
 'bro',
 'brooo',
 'bullsey',
 'call',
 'center',
 'chat',
 'check',
 'checkup',
 'circular',
 'class',
 'close',
 'come',
 'confirm',
 'conflict',
 'connect',
 'contact',
 'content',
 'convo',
 'creator',
 'daili',
 'deadlin',
 'deliveri',
 'depart',
 'discount',
 'discuss',
 'doc',
 'doctor',
 'drop',
 'due',
 'emerg',
 'even',
 'everi',
 'everyon',
 'exactli',
 'examin',
 'exclus',
 'expect',
 'eye',
 'fasttt',
 'fav',
 'favorit',
 'file',
 'final',
 'fire',
 'fix',
 'flash',
 'free',
 'fresh',
 'friend',
 'funni',
 'game',
 'giveaway',
 'got',
 'group',
 'grp',
 'handshak',
 'headphon',
 'home',
 'hospit',
 'hot',
 'hr',
 'huge',
 'hurri',
 'hw',
 'immedi',
 'import',
 'intern',
 'interview',
 'item',
 'join',
 'keyboard',
 'laptop',
 'latest',
 'learn',
 'like',
 'limit',
 'linkedin',
 'live',
 'lobbi',
 'lock',
 'machin',
 'massiv',
 'materi',
 'may',
 'medic',
 'meet',
 'member',
 'meme',
 'mention',
 'messag',
 'min',
 'monday',
 'morn',
 'msg',
 'mtg',
 'nearest',
 'need',
 'network',
 'new',
 'next',
 'night',
 'note',
 'notic',
 'offer',
 'onlin',
 'order',
 'packag',
 'pdf',
 'phone',
 'pick',
 'pl',
 'placement',
 'pleas',
 'pm',
 'portal',
 'post',
 'present',
 'product',
 'professor',
 'project',
 'reach',
 'react',
 'receiv',
 'recommend',
 'reel',
 'remind',
 'repli',
 'req',
 'request',
 'respond',
 'review',
 'rn',
 'sale',
 'sched',
 'schedul',
 'see',
 'session',
 'shift',
 'someon',
 'soon',
 'squad',
 'start',
 'stori',
 'studi',
 'submiss',
 'submit',
 'suggest',
 'surpris',
 'tag',
 'team',
 'technologist',
 'thread',
 'tmw',
 'today',
 'tomorrow',
 'tonight',
 'tonighttt',
 'tournament',
 'train',
 'trend',
 'tri',
 'updat',
 'upload',
 'ur',
 'urgent',
 'vid',
 'video',
 'viral',
 'visit',
 'vlog',
 'wait',
 'want',
 'warn',
 'watch',
 'workshop']

In [207]:
feature_order2 = model2.drop(columns=["priority_score"]).columns.tolist()
feature_order2

['battery_level',
 'screen_on',
 'headset_connected',
 'weekday',
 'notification_frequency_today',
 'app_usage_minutes_today',
 'app_open_frequency',
 'notification_clicked',
 'notification_dismissed',
 'model1_priority_label_HIGH',
 'model1_priority_label_LOW',
 'model1_priority_label_MEDIUM',
 'app_name_Calendar',
 'app_name_Discord',
 'app_name_Gmail',
 'app_name_Instagram',
 'app_name_LinkedIn',
 'app_name_Teams',
 'app_name_Telegram',
 'app_name_Twitter',
 'app_name_WhatsApp',
 'app_name_YouTube',
 'time_of_day_afternoon',
 'time_of_day_evening',
 'time_of_day_morning',
 'time_of_day_night']

In [ ]:
pickle.dump(feature_order1, open('feature_order_model1.pkl', 'wb'))
pickle.dump(feature_order2, open('feature_order_model2.pkl', 'wb'))
pickle.dump(oer_app, open('oer_app.pkl', 'wb'))
pickle.dump(dr, open('test_retrain_model.pkl', 'wb'))